name: Node.js CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 15.x]

    steps:
      - uses: actions/checkout@v2
      - name: Install and Enable spamassassin and spamc
        run: |
          sudo apt-get update -qq
          sudo apt-get install spamassassin spamc
          sudo sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/spamassassin
          sudo systemctl start spamassassin
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build --if-present
      - run: sudo npm test
